name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - '1.6.x'
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get update
          sudo apt-get -y install linux-libc-dev linux-headers-generic build-essential
          sudo apt-get -y install
          npm install -g node-gyp
          curl https://nodejs.org/download/release/v19.9.0/node-v19.9.0-headers.tar.gz --output headers.tar.gz
          tar -xvzf headers.tar.gz
          sudo mv node-v19.9.0/include/node /usr/include

      - run: nimble install -Y
      - run: nim c --gc:arc -d:release -d:denimcli -d:danger --opt:size -r src/${{ github.event.repository.name }}.nim
      - run: nimble test
